########################################
#
# This is a SIMPLE slurm.conf file example
#
########################################
ControlMachine=slurm_master    # CHANGE IT!
ControlAddr=10.0.2.3           # CHANGE IT!
ClusterName=mycluster          # CHANGE IT!
SlurmctldPidFile=/var/run/slurmctld.pid
SlurmdPidFile=/var/run/slurmd.pid
SlurmdSpoolDir=/var/spool/slurmd
SlurmUser=slurm
StateSaveLocation=/var/spool/slurmctld
SwitchType=switch/none
TaskPlugin=task/affinity

#
# TIMERS                     # Values you may want to change in future
#KillWait=30                 # SIGTERM/SIGKILL interval on job kill
#MinJobAge=300               # Remove ended job info from scontrol after 300 sec
#SlurmctldTimeout=120        # After 120 sec backup controller takes control
#SlurmdTimeout=300           # Mark node DOWN after 300 sec id slurmd did not respond
#SchedulerTimeSlice=30
#
# SCHEDULING
SchedulerType=sched/backfill
SelectType=select/linear          # This will take whole nodes for each job!
PriorityType=priority/multifactor
#PriorityWeightFairshare=         # Tune weights for flexible priority
#DefMemPerCPU=0
#MaxMemPerCPU=0
#
# LOGGING
#SlurmctldDebug=info
SlurmctldLogFile=/var/log/slurmctld.log
#SlurmdDebug=info
SlurmdLogFile=/var/log/slurmd.log
DebugFlags=                             # May be useful later, e.g. Backfill,Gres,JobComp,Priority
#
# ACCOUNTING
# NO DATABSE ACCOUNTING OPTION, sacct/sacctmgr are almost useless in this case
# AccountingStorageType=accounting_storage/filetext
#
# DATABASE OPTION, set up mysql first!
AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=slurm_db          # CHANGE IT!
AccountingStoragePass=MYPASSWORD        # CHANGE IT!
JobCompType=jobcomp/none
# OR:
# JobCompType=taskcomp/filetxt            # Log completed jobs into
# JobCompLoc=/var/log/slurm/jobcomp.log   # <- this file

JobAcctGatherType=jobacct_gather/cgroup # taskacct_gather/none to disable
ProctrackType=proctrack/cgroup
# Plugins
# JobSubmitPlugins=lua                  # You need to have job_submit.lua
#                                       # Take a look at https://github.com/NVIDIA/slurm-lua-jobsubmit-framework
#
# COMPUTE NODES
NodeName=node[1-10] State=UNKNOWN
PartitionName=def Nodes=node[1-10] Default=YES \
  MaxTime=2-00:00:00 State=UP

